version: "3"
services:
  web-app:
    image: list-app-dev
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - list-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    env_file: ./server/config/dev.env
    ports:
      - "5000:5000"
    networks:
      - list-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - list-app
    volumes:
      - mongo-data:/data/db
networks:
  list-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local