### Check is server is on
GET http://localhost:5000/

### Get All
GET http://localhost:5000/api/movies

### Get One
GET http://localhost:5000/api/movie/1 HTTP/1.1

### Add 
POST http://localhost:5000/api/movie HTTP/1.1
content-type: application/json

{
    "name": "Test 1",
    "rating": 8,
    "time": ["9:00", "12:00" , "15:00" ]
}

### Delete One
DELETE http://localhost:5000/api/movie/60997c16ce102500695b4cf7 HTTP/1.1
